# https://www.playframework.com/documentation/latest/Configuration

# Database configuration for Quill (MySQL)
db {
  dataSourceClassName = "com.mysql.cj.jdbc.MysqlDataSource"
  dataSource {
    url = "jdbc:mysql://localhost:3306/vantage_perks?useSSL=false&serverTimezone=UTC"
    user = "root"
  }
}

# Typesense Configuration
typesense {
  protocol = "http"
  host = "localhost"
  port = 8108
  apiKey = "xyz_123_your_secret_api_key"
}
