# https://www.playframework.com/documentation/latest/Configuration

# Database configuration for Quill (MySQL)
db {
  dataSourceClassName = "com.mysql.cj.jdbc.MysqlDataSource"
  dataSource {
    url = "jdbc:mysql://localhost:3306/vantage_demo_db?useSSL=false&serverTimezone=UTC"
    user = "root"
  }
}

# Typesense Configuration
typesense {
  protocol = "https"
  host = ""
  port = 443
  apiKey = ""
}
